spring.application.name=Zent


 #Iniciamos informacion general de la base de datos
spring.datasource.url = jdbc:h2:mem:Zent_db
spring.datasource.username = sa
spring.datasource.password = 

#Iniciamos base de datos virtual
spring.h2.console.enabled = true
spring.h2.console.path = /h2-console

#Activacion de JPA

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
